# Generated by Django 4.2 on 2024-11-03 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scrum', '0002_alter_tarea_responsable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarea',
            options={'permissions': [('permisoMarcarTarea', 'Puede marcar una tarea como completada.')]},
        ),
        migrations.AlterField(
            model_name='tarea',
            name='responsable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
